### ISSUE TITLE
Add Conditional Execution beforeAgent Note

### ISSUE THREAD

**Issue by jhendrick** [cloudbees-cd-acceleration-workshop/cloudbees-cd-acceleration-workshop-exercises#2]
In the Conditional Execution section in the pipeline we're using:

beforeAgent true

May be beneficial to include a note as to why you would want to do this an the significance of what is means.  This potentially saves us time in needing to spin up a new agent pod if the branch isn't the master branch.

**Comment by jhendrick** [comment]
Also #3 below this section it says:

"Next, in GitHub, navigate to your forked helloworld-nodejs repository - click on the Branch drop down menu, type *development"

Remove the * in front of development, that might be confusing.

**Comment by kmadel** [comment]
Done https://github.com/cloudbees-cd-acceleration-workshop/cloudbees-cd-acceleration-workshop-exercises/commit/a1f05dca469790f480bb1e989627d37398371e43

Thanks
